info:
  description: Petstore Eureka Service Discovery
eureka:
  server:
    enableSelfPreservation: false
    
---

spring:
  profiles: cloud
  
eureka:
  instance:
    nonSecurePort: 80

---

spring:
  profiles: discovery1
  
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service-2.credentials.uri:http://127.0.0.1:8762/eureka/}

---

spring:
  profiles: discovery2
  
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:127.0.0.1}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service-1.credentials.uri:http://localhost:8761/eureka/}
