info:
  description: Edge gateway to the application
  
spring:
  application:
    name: user-interface
  cloud:
    config:
      enabled: false
      discovery:
        enabled: true

zuul:
  prefix: 
  stripPrefix: true
  ignoredServices: '*'
  sensitiveHeaders: 
  routes:
    data:
      sensitiveHeaders: Cookie, Set-Cookie, Authorization
      path: /api/v1/data/**
      serviceId: data-service
    auth:
      sensitiveHeaders: Cookie, Set-Cookie, Authorization
      path: /api/v1/auth/**
      serviceId: auth-service
      
ribbon:
  ReadTimeout: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

---

spring:
  profiles: cloud
  
#ribbon:
#  IsSecure: true