server:
  port: ${vcap.application.port:8080}

info:
  description: Edge gateway to the application
  
spring:
  application:
    name: user-interface
  cloud:
    config:
      enabled: false
      discovery:
        enabled: true

zuul:
  prefix: 
  stripPrefix: true
  ignoredServices: '*'
  sensitiveHeaders: 
  routes:
    data:
      sensitiveHeaders: Cookie, Set-Cookie, Authorization
      path: /api/v1/data/**
      serviceId: data-service
    auth:
      sensitiveHeaders: Cookie, Set-Cookie, Authorization
      path: /api/v1/auth/**
      serviceId: auth-service
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/}
  instance:
    hostname: ${vcap.application.uris[0]:localhost}

ribbon:
  ReadTimeout: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

---

spring:
  profiles: cloud
  
eureka:
  instance:
    securePortEnabled: true
    securePort: 443
    nonSecurePortEnabled: false
    nonSecurePort: 80
    homePageUrl: https://${vcap.application.uris[0]}/
    infoUrl: https://${vcap.application.uris[0]}/info
    healthUrl: https://${vcap.application.uris[0]}/health
    
ribbon:
  IsSecure: true